### PR TITLE
Update handbook.md

### PR DESCRIPTION
**Pull request by vkahmann**
Equal Opportunity Employment section: Updated Meg's email address to meg@dbtlabs.com

Expense Policies section: Replaced expense form link with airbase

Plan for Leave section: Updated Meg's email address

Initial Office Setup - New Hires  section: Replaced expense form with airbase on 2 separate lines, "Process to expense" 

Reimbursement Process section: Replaced the expense form with airbase and edited the existing instructions for what to add in the category/notes for Airbase.

### CODE REVIEW

**Review by megcolon — APPROVED** [review]
This is great, thank you so much!

**Comment by arieldbt** [comment]
Thoughts on merging this change @vkahmann or @megcolon?

Just submitted the same changes and think* they are still relevant.

**Comment by jthandy** [comment]
@megcolon we never merged this...do we still need to merge it or can we close?

**Comment by megcolon** [comment]
> @megcolon we never merged this...do we still need to merge it or can we close?

@jthandy Thank you! I merged #56 but this one can be canceled, it was included elsewhere.

**Pull request closed without merging**
